language: java
jdk: oraclejdk8
script: mvn clean verify assembly:single -U -B -fae
cache: apt
before_script:
- sudo apt-get update
- sudo apt-get install s3cmd
- echo "secret_key = $AWS_SECRET" >>.s3cfg
- echo "access_key = $AWS_ACCESS" >>.s3cfg
- s3cmd --config=.s3cfg get s3://unit-test-resources/FolioHlp.zip FolioHlp.zip
- ./mkres.sh
after_script:
- rm -rf FolioHlp.zip path files
env:
  global:
  - secure: vww7E2brbU9oNj/inaKG8icdNZAPOluaBEmQsEW3XsXtIsTozzB6rmM3qSXXsQyOJnXJb/wT3tuoRgyIle6mIDSYTsiqBX/25So4Ng1m3NlXvwUE/DEtTS9zQ6zQD1C9O+WTfViCqfIAUhE0gRZ3oUBbBvmTSzzBnQcdXmqli7E=
  - secure: Wx1TaRBATk+3omGaBp45lLdwkDPRbBg7H7Bq8GMpfOMI0QT+gEulSJ9EE5p7Nztsox/ricjHDNNttmFyxVOskimCqs7BLtGS74ks+4oMk2dzLPz79kmGB8IdP5CCtijk3cv+/gSqxMKt4FGqx0HdQIIhY+02X5ZpyYWnz8gu3uE=
before_deploy: git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: jBPZueLjmX6FIOLT50rS1xW1PHY++fV2t2bf0BE9C/eP/A4OccFtL1N+9/VOICGDoE/zHagJ3pvUO1JZuvfbn12ZS6Ig6x/9e2wuBGiPxg8ZkHgLSmVjzsbOgugTSi9mv5WAuBt3EI3wu79HQFSWGntuMvasryyauvnMXtbWcTA=
  file: 
    - "commandline/target/folioxml-commandline-jar-with-dependencies.jar"
    - "commandline/target/folioxml-commandline.jar"
    - "core/folioxml/target/folioxml-core.jar"
    - "contrib/folioxml-lucene/target/folioxml-lucene.jar"
    - "diff_match_patch/target/diff_match_patch.jar"
  skip_cleanup: true
  on:
    repo: imazen/folioxml
    all_branches: true
    tags: true